adminUser: admin
adminPassword: grafana123

service:
  type: LoadBalancer

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus-server.monitoring2285.svc.cluster.local

sidecar:
   dashboards:
     enabled: true
     label: grafana_dashboard
     folder: /var/lib/grafana/dashboards
     searchNamespace: ALL

