apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-metrics-demo
  namespace: demo2285
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-metrics-demo
  template:
    metadata:
      labels:
        app: python-metrics-demo
    spec:
      containers:
        - name: python-metrics-demo
          image: 227295996532.dkr.ecr.ap-northeast-1.amazonaws.com/python-metrics-demo:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-metrics-demo
  namespace: demo2285
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: python-metrics-demo

